sudo: required
services:
  - docker

before_install:
  - docker build -t yannick3dimerce/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run yannick3dimerce/react-test npm test -- --coverage

after_success:
  - docker build -t yannick3dimerce/multi-client ./client
  - docker build -t yannick3dimerce/multi-nginx ./nginx
  - docker build -t yannick3dimerce/muli-server ./server
  - docker build -t yannick3dimerce/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yannick3dimerce/multi-client
  - docker push yannick3dimerce/multi-nginx
  - docker push yannick3dimerce/muli-server
  - docker push yannick3dimerce/multi-worker